#!/bin/bash

: ${1?"arg1 <device> is missing"} || exit 1

dev=$1
dev_path="/sys/block/${dev}/queue"
logs="./data"
name=$(uname -n | cut -d"." -f1)
rev=$(uname -r)
tag="1"

logfile="${logs}/${name}_${rev}_${tag}.out"

for i in $(find $dev_path -type f)
do
	echo $i
	cat $i
done > $logfile
